version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - MONGO_URI=mongodb://mongoadmin:secret@db:27017/todos?authSource=admin
      - JWT_ALGORITHM=RS256
      - JWT_EXPIRES_IN=5m
    depends_on:
      - db
    command: bash -c "
      wget -q https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
      chmod +x ./wait-for-it.sh &&
      bash ./wait-for-it.sh -s db:27017 -- npm start"
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
